const test=require('node:test'),assert=require('node:assert/strict');
const {createInitialGameState}=require('../.server-dist/game/rules');
const {createLocationTextWorld}=require('../.server-dist/game/text-world/world');
const {shelterTextRooms,withDefaultShelterRooms}=require('../.server-dist/game/text-world/shelter-definitions');
const {localWorkEnvironment,activityConditionState,consumeWorkInputs}=require('../.server-dist/game/work-environment');
const {activityInputsAvailable}=require('../.server-dist/game/activity');
const {choiceConditionsMet}=require('../.server-dist/game/content-engine');
const {buildRuntimeRegistry}=require('../.server-dist/game/runtime-registry');
const {migrateTextWorld}=require('../.server-dist/game/text-world/world');
const {TextRoomSchema}=require('../.server-dist/game/schemas/text-world');
const {textRoomIssues}=require('../.server-dist/game/text-world/validation');
function setup(){const state=createInitialGameState(),world=createLocationTextWorld(shelterTextRooms());state.locationTextWorlds.shelter=world;
 world.observations.shelter_storage={stages:['outline','surface','interior'],collected:false};world.observations.shelter_workbench={stages:['outline','surface'],collected:false};
 world.entities.goods={id:'goods',name:'고철',description:'고철',inventoryRegistered:true,components:{position:{zone:'shelter_storage',relation:'inside'},portable:{itemId:'scrapMetal',amount:3}}};world.entities.shelter_storage.components.container.items=['goods'];state.inventory.scrapMetal=0;
 return {state,world};}
const recipe={id:'custom',activity:{kind:'craft'},conditions:[{type:'has_item',itemId:'scrapMetal',amount:2}],effects:[{type:'remove_item',itemId:'scrapMetal',amount:1},{type:'remove_item',itemId:'scrapMetal',amount:1},{type:'advance_time',minutes:10}]};
test('only open, known, local, unowned storage supplies recipes and queries never mutate state',()=>{const {state,world}=setup(),before=structuredClone(state);
 assert(choiceConditionsMet(recipe,state));assert(activityInputsAvailable(recipe,state));assert.equal(activityConditionState(recipe,state).inventory.scrapMetal,3);assert.deepEqual(state,before);
 world.entities.shelter_storage.components.openable.isOpen=false;assert(!choiceConditionsMet(recipe,state));assert(!localWorkEnvironment(state,'craft').sources.length);
 world.entities.shelter_storage.components.openable.isOpen=true;world.entities.goods.inventoryRegistered=false;assert(!activityInputsAvailable(recipe,state));
 world.entities.goods.inventoryRegistered=true;world.entities.shelter_storage.components.ownership={npcId:'shumi'};assert(!activityInputsAvailable(recipe,state));
 delete world.entities.shelter_storage.components.ownership;state.location='forest';assert(!activityInputsAvailable(recipe,state));
});
test('mixed carried and stored payments aggregate repeated costs and missing inputs never partially consume stacks',()=>{const {state,world}=setup();state.inventory.scrapMetal=1;
 const paid=consumeWorkInputs(state,recipe,recipe.effects.slice(0,2),{scrapMetal:2});assert.deepEqual(paid.storedItems,{scrapMetal:1});assert.equal(paid.inputs.reduce((n,e)=>n+(e.amount??0),0),1);assert.equal(world.entities.goods.components.portable.amount,2);
 const before=structuredClone(state);assert.throws(()=>consumeWorkInputs(state,recipe,recipe.effects,{scrapMetal:5}),/부족/);assert.deepEqual(state,before);
 state.locationTextWorlds.shelter=migrateTextWorld(world);assert.equal(localWorkEnvironment(state,'craft').sources[0].amount,2);
});
test('only a known working station improves compatible work; destruction, darkness and carrying it disable the bonus',()=>{const {state,world}=setup(),bench=world.entities.shelter_workbench;
 assert(!localWorkEnvironment(state,'craft').station);bench.components.structure.integrity=5;assert.equal(localWorkEnvironment(state,'craft').station.durationMultiplier,0.8);
 assert(!localWorkEnvironment(state,'cook').station);world.rooms.shelter_work_corner.light=false;assert(!localWorkEnvironment(state,'craft').station);world.rooms.shelter_work_corner.light=true;
 bench.components.position.zone='player';assert(!localWorkEnvironment(state,'craft').station);
});
test('default shelter content validates and respects an authored replacement',()=>{const registry=buildRuntimeRegistry(),rooms=shelterTextRooms();rooms.forEach(r=>TextRoomSchema.parse(r));assert.deepEqual(textRoomIssues(rooms,new Set(Object.keys(registry.items))),[]);
 const custom={locations:{shelter:{}},textRooms:[{...rooms[0],id:'my_room'}]};assert.strictEqual(withDefaultShelterRooms(custom),custom);
});


test('storing and recrafting tools preserves each tool wear through saves and breaking one leaves the other intact',()=>{
 const {state,world}=setup();state.inventory.utilityKnife=1;state.toolDurability.utilityKnife=3;world.active=true;world.player.zone='shelter_work_corner';
 const {materializeOwnedInventory}=require('../.server-dist/game/text-world/inventory');
 const {resolveWorldActions}=require('../.server-dist/game/text-world/engine');
 const {applyEffect}=require('../.server-dist/game/state-utils');
 const {normalizeGameSession}=require('../.server-dist/game/repository');
 const {reconcileWorldInventory}=require('../.server-dist/game/text-world/inventory-state');
 materializeOwnedInventory(state,world,buildRuntimeRegistry(state));
 const old=Object.values(world.entities).find(e=>e.components.portable?.itemId==='utilityKnife');
 const beforeStore=structuredClone(state),{applySystemNote}=require('../.server-dist/game/rules');
 let result=resolveWorldActions(world,state,[{type:'HOLD',target:old.id},{type:'MOVE',target:'shelter_storage'},{type:'PUT',target:old.id,destination:'shelter_storage',relation:'inside'}]);assert(!result.interrupted);
 applySystemNote(beforeStore,state);assert(!state.systemNote.includes('파손'),'storing a tool is not breaking it');
 assert.equal(state.inventory.utilityKnife??0,0);assert.equal(old.toolDurability,3);assert.equal(state.toolDurability.utilityKnife,undefined);
 applyEffect({type:'add_item',itemId:'utilityKnife',amount:1},state);applyEffect({type:'set_tool_durability',itemId:'utilityKnife',value:10},state);
 assert.equal(old.toolDurability,3,'creating another knife never repairs the stored knife');
 const fresh=Object.values(world.entities).find(e=>e.id!==old.id&&e.components.portable?.itemId==='utilityKnife');assert.equal(fresh.toolDurability,10);
 const saved=normalizeGameSession({id:'tool-ownership',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),state:JSON.parse(JSON.stringify(state)),world:{locationCards:{},itemCards:{},personCards:{},sceneCards:{},eventCards:{},protagonistCard:null}}).state;
 const restored=saved.locationTextWorlds.shelter;
 result=resolveWorldActions(restored,saved,[{type:'TAKE',target:old.id}]);assert(!result.interrupted);assert.equal(saved.inventory.utilityKnife,2);assert.equal(saved.toolDurability.utilityKnife,3);
 applyEffect({type:'damage_tool',itemId:'utilityKnife',amount:1},saved);assert.equal(restored.entities[old.id].toolDurability,2);assert.equal(restored.entities[fresh.id].toolDurability,10);
 applyEffect({type:'damage_tool',itemId:'utilityKnife',amount:2},saved);reconcileWorldInventory(saved);
 assert.equal(saved.inventory.utilityKnife,1);assert.equal(saved.toolDurability.utilityKnife,10);assert.equal(restored.entities[old.id].components.position.zone,'consumed');assert.equal(restored.entities[fresh.id].components.position.zone,'player');
});
